//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//
//

import AWSCore
import AWSCognitoIdentityProvider


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-west-2_6s4rUEJZl"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "62k6q79psg1lpdfous1hkn4mgd"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USWest2

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "17245nij7kqf4f9eb6agbndrcke7acop6vm9vterneq0i2vdaiqp"


