
//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import UIKit
import AWSMobileHubHelper
import AWSDynamoDB

class MainViewController: UIViewController {
   
    var willEnterForegroundObserver: AnyObject!
    
    let objectMapper = AWSDynamoDBObjectMapper.default()
    @IBOutlet weak var mainScrollView: UIScrollView!
    @IBOutlet weak var noMatches: UILabel!
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        /*if !(AWSIdentityManager.default().isLoggedIn) {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let viewController = storyboard.instantiateViewController(withIdentifier: "SignIn")
            present(viewController, animated: true, completion: nil)
        }
        else{
            willEnterForegroundObserver = NotificationCenter.default.addObserver(forName: NSNotification.Name.UIApplicationWillEnterForeground, object: nil, queue: OperationQueue.current) { _ in
            }
            super.viewDidLoad()
        }
        */
        super.viewDidLoad()
        /*let identityManager = AWSIdentityManager.default()
        objectMapper.load(UserInfo.self, hashKey: identityManager.identityId as Any, rangeKey:nil).continueWith(block: { (task:AWSTask<AnyObject>!) -> Any? in
            if let error = task.error as NSError? {
                print("The request failed. Error: \(error)")
            }
            else if (task.result as? UserInfo) != nil {
                // Do something with task.result.
                print("Please print: ", task.result as Any)
            }
            let user = task.result as! UserInfo
            print(user)
            return nil
        })
         */
        

        
       
    }
  
}

