//
//  UserInfo.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class UserInfo: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _allUsers: [String]?
    var _bio: String?
    var _firstName: String?
    var _graphRequest: String?
    var _lastName: String?
    var _matches: [String]?
    var _rejected: [String]?
    
    class func dynamoDBTableName() -> String {
        
        return "buddyup-mobilehub-1267115472-UserInfo"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_allUsers" : "allUsers",
            "_bio" : "bio",
            "_firstName" : "firstName",
            "_graphRequest" : "graphRequest",
            "_lastName" : "lastName",
            "_matches" : "matches",
            "_rejected" : "rejected",
        ]
    }
}
