//
//  Login.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Login: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _username: String?
    var _bios: String?
    var _hashTags: [String]?
    var _musicPref: [String]?
    var _password: String?
    
    class func dynamoDBTableName() -> String {

        return "buddyup-mobilehub-1267115472-Login"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_username"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_username" : "username",
               "_bios" : "bios",
               "_hashTags" : "hashTags",
               "_musicPref" : "musicPref",
               "_password" : "password",
        ]
    }
}
