//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-west-2_X0Wwq5DSv"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "1gnk2t2pnbqv7p1u54pao0t1ua"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USWest2

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1gde9mfshh1nq5vh6rvq1fnvpvq0hj97ssh51390ailgi9q3g2sj"
